config/routes.rb
Rails.application.routes.draw do

  get 'login',  to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  resources :sessions, only: [:create]

  resources :contacts do
    get 'delete', on: :member
  end

  get "avatar/:size/:background/:text" => Dragonfly.app.endpoint { |params, app|
    app.generate(:initial_avatar, URI.unescape(params[:text]), { size: params[:size], background_color: params[:background] })
  }, as: :avatar

  root to: 'contacts#index'
end

app/models/concerns/avatarable.rb
module Avatarable
  extend ActiveSupport::Concern

  AVATAR_COLORS = [ 'e53935', 'b71c1c', 'd81b60', '880e4f', '8e24aa', '4a148c',
    '5e35b1', '311b92', '3949ab', '1a237e', '1e88e5', '0d47a1', '039be5', '01579b',
    '00acc1', '006064', '00897b', '004d40', '43a047', '1b5e20', '7cb342', '33691e',
    'c0ca33', '827717', 'fdd835', 'f57f17', 'ffb300', 'ff6f00', 'fb8c00', 'e65100',
    'f4511e', 'bf360c', '6d4c41', '3e2723', '757575', '212121', '546e7a', '263238' ]

  included do
    delegate :url_helpers, to: 'Rails.application.routes'
  end

  def avatar_url
    url_helpers.send(:avatar_path, avatar_size, avatar_color, avatar_text)
  end

  def avatar_size
    150
  end

  def avatar_param
    to_param
  end

  def avatar_text
    raise NotImplementedError, "must implement avatar_text"
  end

  def avatar_color
    AVATAR_COLORS[ Zlib.crc32( avatar_param ).modulo( AVATAR_COLORS.length ) ]
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  include Avatarable

  # paperclip attachment
  has_attached_file :photo, styles: { thumb: '150x150#' }

  # associations
  belongs_to :user

  # validations
  validates :first_name, :last_name, :email, presence: true
  validates_attachment :photo,
    content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

  # callbacks
  before_validation { photo.clear if remove_photo == '1' }

  attr_accessor :remove_photo

  def full_name
    [first_name, last_name].join(' ')
  end

  # required for avatarable
  def avatar_text
    first_name.chr
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  # associations
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    if current_user.nil?
      redirect_to login_url
    end
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_contact_for_user, except: [:index, :new, :create]

  # GET /contacts
  def index
    @contacts = current_user.contacts.all.order(:last_name, :first_name)
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # POST /contacts
  def create
    @contact = current_user.contacts.build(contact_params)

    if @contact.save
      redirect_to @contact, notice: 'Contact successfully created!'
    else
      render 'new'
    end
  end

  # GET /contacts/:id
  def show
  end

  # GET /contacts/:id/edit
  def edit
  end

  # PUT /contacts/:id
  def update
    if @contact.update_attributes(contact_params)
      redirect_to @contact, notice: 'Contact successfully updated!'
    else
      render 'edit'
    end
  end

  # GET /contacts/:id/delete
  def delete
  end

  # DELETE /contacts/:id
  def destroy
    @contact.destroy
    redirect_to contacts_path, notice: 'Contact successfully removed!'
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :phone_number, :photo, :remove_photo)
  end

  def find_contact_for_user
    @contact = current_user.contacts.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'login'

  # GET /login
  def new
  end

  # POST /sessions
  def create
    user = User.find_by_login(params[:login])
    if user.try(:authenticate, params[:password])
      session[:user_id] = user.id

      redirect_to root_path
    else
      flash.now[:error] = "Invalid login or password"
      render 'new'
    end
  end

  # GET /logout
  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def contact_avatar(contact, options = {})
    if contact.photo.file?
      image_tag contact.photo.url(:thumb), options
    else
      image_tag contact.avatar_url, options
    end
  end
end

app/views/contacts/_form.html.erb
<div class="form-group row">
  <div class="col-sm-6 col-xs-10">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, :class => 'form-control' %>
  </div>
</div>

<div class="form-group row">
  <div class="col-sm-6 col-xs-10">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, :class => 'form-control' %>
  </div>
</div>

<div class="form-group row">
  <div class="col-sm-6 col-xs-10">
    <%= f.label :email %>
    <%= f.text_field :email, :class => 'form-control', :placeholder => 'e.g. john@exmaple.com' %>
  </div>
</div>

<div class="form-group row">
  <div class="col-sm-6 col-xs-10">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, :class => 'form-control', :placeholder => 'e.g. 555-555-5555' %>
  </div>
</div>

<div class="form-group row">
  <div class="col-sm-6 col-xs-10">
    <%= f.label :photo %>
    <div class="input-group">
      <span class="input-group-btn">
        <span class="btn btn-default btn-file">
          Browse&hellip; <%= f.file_field :photo %>
        </span>
      </span>
      <input type="text" class="form-control" readonly>
    </div>
  </div>
</div>

<% unless f.object.new_record? || !f.object.photo.file? %>
<div class="checkbox">
  <label>
    <%= f.check_box :remove_photo %> Delete existing photo?
  </label>
</div>
<% end %>

<div class="form-actions">
  <%= f.submit submit_text, :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', cancel_link, :class => 'btn btn-default' %>
</div>

app/views/contacts/delete.html.erb
<div class="page-header">
  <h3>Delete Contact</h3>
</div>

<div class="alert alert-warning">
  <p>Are you sure you want to delete this contact? This action cannot be undone.</p>
</div>

<%= form_tag contact_path(@contact), :method => :delete do %>
  <div class="form-actions">
    <%= submit_tag 'Yes, Delete Contact', :class => 'btn btn-danger' %>
    <%= link_to 'No', contact_path(@contact), :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="page-header">
  <h3>Edit Contact</h3>
</div>

<%= render :partial => "shared/validation_errors", :locals => {:target => @contact} %>

<%= form_for @contact, :html => { :role => 'form' } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f, :submit_text => 'Update Contact', :cancel_link => contact_path(@contact) } %>
<% end %>

app/views/contacts/index.html.erb
<div class="page-header">
  <h3>Contacts</h3>
  <div class="actions">
    <%= link_to 'New Contact', new_contact_path, :class => 'btn btn-primary' %>
  </div>
</div>

<div class="list-group">
<% @contacts.each do |contact| %>
  <%= link_to contact_path(contact), class: 'list-group-item' do %>
    <div class="media">
      <div class="media-left padding-3x media-middle">
        <%= contact_avatar(contact, class: 'media-object img-circle', style: 'width:64px;height:64px;') %>
      </div>
      <div class="media-body media-middle contact-name">
        <p><strong><%= contact.full_name %></strong></p>
      </div>
      <div class="media-body media-middle contact-email hidden-xs">
        <p><%= contact.email %></p>
      </div>
      <div class="media-body media-middle contact-phone hidden-xs">
        <p><%= contact.phone_number %></p>
      </div>
    </div>
  <% end %>
<% end %>
</div>

app/views/contacts/new.html.erb
<div class="page-header">
  <h3>New Contact</h3>
</div>

<%= render :partial => "shared/validation_errors", :locals => {:target => @contact} %>

<%= form_for @contact, :html => { :role => 'form' } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f, :submit_text => 'Create Contact', :cancel_link => contacts_path } %>
<% end %>

app/views/contacts/show.html.erb
<div class="page-header">
  <h3>Contact Details</h3>
  <div class="actions">
    <%= link_to 'View All', contacts_path, class: 'btn btn-default btn-transborder' %>
  </div>
</div>

<%= render :partial => 'shared/notice_or_error' %>

<div class="media">
  <div class="media-left padding-4x media-middle">
    <%= contact_avatar(@contact, class: 'media-object img-circle') %>
  </div>
  <div class="media-body media-middle">
    <h4>Full Name</h4>
    <%= @contact.full_name %>

    <h4>Email</h4>
    <%= @contact.email %>

    <h4>Phone Number</h4>
    <%= @contact.phone_number %>
  </div>
</div>

<div class="form-actions">
  <%= link_to 'Edit Contact', edit_contact_path(@contact), :class => 'btn btn-primary' %>
  <%= link_to 'Delete Contact', delete_contact_path(@contact), :class => 'btn btn-default' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <title>Contacts Manager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Static navbar -->
  <div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Contacts Manager', root_path, class: 'navbar-brand' %>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Log out', logout_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <title>Contacts Manager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_notice_or_error.html.erb
<!-- Render flash notice if present -->
<% if flash[:notice] -%>
<div class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= flash[:notice] %>
</div>
<% end %>
<!-- Render flash error if present -->
<% if flash[:error] -%>
<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= flash[:error] %>
</div>
<% end %>

app/views/shared/_validation_errors.html.erb
<% if target && target.errors.any? %>
  <!-- display errors -->
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h4><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h4>
    <ul>  
      <% target.errors.full_messages.each do |msg| %>  
        <li><%= msg %></li>  
      <% end %>  
    </ul> 
  </div>
<% end -%>